# Generated by Django 4.2.5 on 2023-09-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='first_player_game_winning',
            new_name='first_player_points',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='second_player_game_winning',
            new_name='second_player_points',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
